### ISSUE TITLE
CPU performance in ANMLZoo paper

### ISSUE THREAD

**Issue by karakchi** [jackwadden/ANMLZoo#23]
Hello Jack,

In ANMLZoo paper "ANMLZoo: A Benchmark suite .. ", the CPU performance in Fig 8 appears almost the  same in all the benchmark. I know that each benchmark has different number of states and level of complexity. 

Can you explain why this occurred? how did you produce it via VASim? 

Thank you, 
Rasha

**Comment by jackwadden** [comment]
Note the log axis which can be deceiving. The CPU results actually varied quite wildly from ~150KB/s to 256MB/s (1000x range) and depended on the active set, visited set (see Section V and VI), and node locality.

Also note that VASim is not nearly (not even close) the highest performing CPU engine for automata processing and should not be considered a proxy for CPU performance. We used VASim for these experiments because it was the only tool available at the time that could run the suite, and also offered us visibility into exactly what caused automata processing to be challenging on CPUs. Since then, [hscompile and hsrun](https://github.com/kevinaangstadt/hscompile) have enabled ANML and MNRL automata to be processed using [Intel's Hyperscan](https://github.com/intel/hyperscan) automata processing engine. Hyperscan is extremely sophisticated and benefits from various automata transformations and compute engines and is often many orders of magnitude faster than VASim. Hyperscan even beats spatial architectures in some situations.

**Comment by karakchi** [comment]
Thank you Jack for the reply, 

It was my bad, actually I wanted to ask two questions
1. I meant to ask about the performance of the benchmark is similar when AP is used. 
2.I wanted to verify the way CPU performance calculated (which you have already explained). 

I am sorry for this confusion,

**Comment by jackwadden** [comment]
The caption of Figure 8 explains that "AP performance is estimated to be 133MB/s, however, we expect to see performance degradations due to output reporting constraints when using the real hardware."

It's fine to verify the VASim performance, just note that these results should not be used as representative performance of the CPU for automata processing.

**Comment by karakchi** [comment]
Thanks, Jack!
